# Generated by Django 3.1 on 2020-08-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=20)),
                ('cgpa', models.FloatField()),
                ('year_of_graduation', models.IntegerField()),
            ],
        ),
    ]
